name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch secrets from tawbar
        run: |
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_BACKEND_PROJECT_ID }}/test -H 'Authorization: ${{ secrets.TAWBAR_BACKEND_API_KEY }}' -o ./backend/.env
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_FRONTEND_PROJECT_ID }}/test -H 'Authorization: ${{ secrets.TAWBAR_FRONTEND_API_KEY }}' -o ./frontend/.env

      - name: Build docker images
        run: docker compose build backend

      - name: Install gems
        run: bin/backend/bundle install

      - name: Run rubocop
        run: bin/backend/lint

      - name: Prepare database
        run: bin/backend/run "bundle exec rake db:prepare"

      - name: Run tests
        run: bin/backend/test

  validate-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch secrets from tawbar
        run: |
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_BACKEND_PROJECT_ID }}/test -H 'Authorization: ${{ secrets.TAWBAR_BACKEND_API_KEY }}' -o ./backend/.env
          curl https://api.tawbar.com/projects/v1/${{ secrets.TAWBAR_FRONTEND_PROJECT_ID }}/test -H 'Authorization: ${{ secrets.TAWBAR_FRONTEND_API_KEY }}' -o ./frontend/.env

      - name: Build docker images
        run: docker compose build --build-arg UID=$UID frontend

      - name: Install dependencies
        run: bin/frontend/yarn install

      - name: Build vite
        run: bin/frontend/yarn build

      - name: Run svelte-check
        run: bin/frontend/check

      - name: Run linter
        run: bin/frontend/lint
